### ISSUE TITLE
Add `metadata.yml` in every modules

### ISSUE THREAD

**Issue by Leirof** [Gunivers/Bookshelf#52]
This file must contain:
```yaml
display_name: <name>
description: <short text>
documentation: <link>
thumbnail: <link>
contains:
- [structure_bank]
- [lib]
- [system]
search_trees:
- [path 1]
- [path 2]
```

Todo:
- [ ] global
- [ ] biome
- [ ] bitwise
- [ ] block
- [ ] cache
- [ ] color
- [ ] core
- [ ] example
- [ ] health
- [ ] id
- [ ] item
- [ ] link
- [ ] location
- [ ] mapedit
- [ ] math
- [ ] memory
- [ ] move
- [ ] orientation
- [ ] schedule
- [ ] time
- [ ] tree
- [ ] vector
- [ ] view
- [ ] xp
